### ISSUE TITLE
Implement ESLint rules

### ISSUE THREAD

**Issue by sebmck** [facebookexperimental/rome#94]
Followed is a list of ESLint rules that we should implement.

- [X] enforce `return` statements in getters (getter-return) #129 
- [X] disallow using an async function as a Promise executor (no-async-promise-executor) #101
- [X] disallow comparing against -0 (no-compare-neg-zero) #106
- [X] disallow assignment operators in conditional expressions (no-cond-assign) #116
- [X] disallow the use of debugger (no-debugger) #103
- [X] disallow duplicate arguments in function definitions (no-dupe-args) #99
- [X] disallow duplicate keys in object literals (no-dupe-keys) #98
- [X] disallow a duplicate case label (no-duplicate-case) #100
- [X] disallow empty character classes in regular expressions (no-empty-character-class) #135
- [x] disallow reassigning exceptions in catch clauses (no-ex-assign) @weblancaster
- [x] disallow unnecessary boolean casts (no-extra-boolean-cast) @zinyando
- [X] disallow reassigning function declarations (no-func-assign) #130
- [X] disallow assigning to imported bindings (no-import-assign) #118
- [x] disallow variable or function declarations in nested blocks (no-inner-declarations) @tatchi
- [x] disallow invalid regular expression strings in RegExp constructors (no-invalid-regexp) @KevinKelbie 
- [X] disallow multiple spaces in regular expression literals (no-regex-spaces) #121
- [x] disallow returning values from setters (no-setter-return) @torifat
- [x] disallow sparse arrays (no-sparse-arrays) #91
- [x] disallow unreachable code after return, throw, continue, and break statements (no-unreachable) @JayaKrishnaNamburu
- [X] disallow control flow statements in finally blocks (no-unsafe-finally) #117
- [x] disallow negating the left operand of relational operators (no-unsafe-negation) #89 
- [X] disallow template literal placeholder syntax in regular strings (no-template-curly-in-string) #112
- [X] disallow deleting variables (no-delete-var) #95
- [X] disallow labels that are variable names (no-label-var) #102
- [x] disallow shadowing of restricted names (no-shadow-restricted-names) @mattsjones 
- [X] suggest template literals instead of string concatenation (prefer-template) #138 
- [X] (disallow-var) #107

Please comment if you want to work on one of these and I'll mark you to avoid duplicating work. Mentions next to rules indicate that someone else is working on it. If a PR isn't opened within a few days then it will be up for grabs.

A checkmark indicates an open PR.

**Comment by yangshun** [comment]
I'd like to try working on `no-debugger`

**Comment by weblancaster** [comment]
I started working on `no-delete-var`

**Comment by JayaKrishnaNamburu** [comment]
I would like to try working on `no-unreachable` :

**Comment by tanhauhau** [comment]
I'd like to try on `no-async-promise-executor`

**Comment by zinyando** [comment]
I'd like to try taking on `no-dupe-args`

**Comment by mattsjones** [comment]
Taking a look at `no-dupe-keys`

**Comment by zinyando** [comment]
I'm taking on `no-duplicate-case`

**Comment by gobeli** [comment]
Would take `no-label-var`

**Comment by yangshun** [comment]
I've added links to the ESLint rule documentation, src implementation and test implementation as it might be useful for people working on them.

---

- [ ] enforce `return` statements in getters (`getter-return`)
  - [docs](https://eslint.org/docs/rules/getter-return/) | [src](https://github.com/eslint/eslint/blob/master/lib/rules/getter-return.js) | [test](https://github.com/eslint/eslint/blob/master/tests/lib/rules/getter-return.js) | @tanhauhau
- [ ] disallow using an async function as a Promise executor (`no-async-promise-executor`)
  - [docs](https://eslint.org/docs/rules/no-async-promise-executor/) | [src](https://github.com/eslint/eslint/blob/master/lib/rules/no-async-promise-executor.js) | [test](https://github.com/eslint/eslint/blob/master/tests/lib/rules/no-async-promise-executor.js)
- [ ] disallow comparing against -0 (`no-compare-neg-zero`)
  - [docs](https://eslint.org/docs/rules/no-compare-neg-zero/) | [src](https://github.com/eslint/eslint/blob/master/lib/rules/no-compare-neg-zero.js) | [test](https://github.com/eslint/eslint/blob/master/tests/lib/rules/no-compare-neg-zero.js)
- [ ] disallow assignment operators in conditional expressions (`no-cond-assign`)
  - [docs](https://eslint.org/docs/rules/no-cond-assign/) | [src](https://github.com/eslint/eslint/blob/master/lib/rules/no-cond-assign.js) | [test](https://github.com/eslint/eslint/blob/master/tests/lib/rules/no-cond-assign.js)
- [ ] disallow the use of debugger (`no-debugger`)
  - [docs](https://eslint.org/docs/rules/no-debugger/) | [src](https://github.com/eslint/eslint/blob/master/lib/rules/no-debugger.js) | [test](https://github.com/eslint/eslint/blob/master/tests/lib/rules/no-debugger.js) | @yangshun 
- [ ] disallow duplicate arguments in function definitions (`no-dupe-args`)
  - [docs](https://eslint.org/docs/rules/no-dupe-args/) | [src](https://github.com/eslint/eslint/blob/master/lib/rules/no-dupe-args.js) | [test](https://github.com/eslint/eslint/blob/master/tests/lib/rules/no-dupe-args.js) |  @zinyando 
- [ ] disallow duplicate keys in object literals (`no-dupe-keys`)
  - [docs](https://eslint.org/docs/rules/no-dupe-keys/) | [src](https://github.com/eslint/eslint/blob/master/lib/rules/no-dupe-keys.js) | [test](https://github.com/eslint/eslint/blob/master/tests/lib/rules/no-dupe-keys.js) |  @mattjones
- [ ] disallow a duplicate case label (`no-duplicate-case`)
  - [docs](https://eslint.org/docs/rules/no-duplicate-case/) | [src](https://github.com/eslint/eslint/blob/master/lib/rules/no-duplicate-case.js) | [test](https://github.com/eslint/eslint/blob/master/tests/lib/rules/no-duplicate-case.js) | @zinyando 
- [ ] disallow empty character classes in regular expressions (`no-empty-character-class`)
  - [docs](https://eslint.org/docs/rules/no-empty-character-class/) | [src](https://github.com/eslint/eslint/blob/master/lib/rules/no-empty-character-class.js) | [test](https://github.com/eslint/eslint/blob/master/tests/lib/rules/no-empty-character-class.js)
- [ ] disallow reassigning exceptions in catch clauses (`no-ex-assign`)
  - [docs](https://eslint.org/docs/rules/no-ex-assign/) | [src](https://github.com/eslint/eslint/blob/master/lib/rules/no-ex-assign.js) | [test](https://github.com/eslint/eslint/blob/master/tests/lib/rules/no-ex-assign.js)
- [ ] disallow unnecessary boolean casts (`no-extra-boolean-cast`)
  - [docs](https://eslint.org/docs/rules/no-extra-boolean-cast/) | [src](https://github.com/eslint/eslint/blob/master/lib/rules/no-extra-boolean-cast.js) | [test](https://github.com/eslint/eslint/blob/master/tests/lib/rules/no-extra-boolean-cast.js)
- [ ] disallow reassigning function declarations (`no-func-assign`)
  - [docs](https://eslint.org/docs/rules/no-func-assign/) | [src](https://github.com/eslint/eslint/blob/master/lib/rules/no-func-assign.js) | [test](https://github.com/eslint/eslint/blob/master/tests/lib/rules/no-func-assign.js)
- [ ] disallow assigning to imported bindings (`no-import-assign`)
  - [docs](https://eslint.org/docs/rules/no-import-assign/) | [src](https://github.com/eslint/eslint/blob/master/lib/rules/no-import-assign.js) | [test](https://github.com/eslint/eslint/blob/master/tests/lib/rules/no-import-assign.js)
- [ ] disallow variable or function declarations in nested blocks (`no-inner-declarations`)
  - [docs](https://eslint.org/docs/rules/no-inner-declarations/) | [src](https://github.com/eslint/eslint/blob/master/lib/rules/no-inner-declarations.js) | [test](https://github.com/eslint/eslint/blob/master/tests/lib/rules/no-inner-declarations.js)
- [ ] disallow invalid regular expression strings in RegExp constructors (`no-invalid-regexp`)
  - [docs](https://eslint.org/docs/rules/no-invalid-regexp/) | [src](https://github.com/eslint/eslint/blob/master/lib/rules/no-invalid-regexp.js) | [test](https://github.com/eslint/eslint/blob/master/tests/lib/rules/no-invalid-regexp.js)
- [ ] disallow multiple spaces in regular expression literals (`no-regex-spaces`)
  - [docs](https://eslint.org/docs/rules/no-regex-spaces/) | [src](https://github.com/eslint/eslint/blob/master/lib/rules/no-regex-spaces.js) | [test](https://github.com/eslint/eslint/blob/master/tests/lib/rules/no-regex-spaces.js)
- [ ] disallow returning values from setters (`no-setter-return`)
  - [docs](https://eslint.org/docs/rules/no-setter-return/) | [src](https://github.com/eslint/eslint/blob/master/lib/rules/no-setter-return.js) | [test](https://github.com/eslint/eslint/blob/master/tests/lib/rules/no-setter-return.js)
- [x] disallow sparse arrays (`no-sparse-arrays`)
  - [docs](https://eslint.org/docs/rules/no-sparse-arrays/) | [src](https://github.com/eslint/eslint/blob/master/lib/rules/no-sparse-arrays.js) | [test](https://github.com/eslint/eslint/blob/master/tests/lib/rules/no-sparse-arrays.js) | #91
- [ ] disallow unreachable code after return, throw, continue, and break statements (`no-unreachable`)
  - [docs](https://eslint.org/docs/rules/no-unreachable) | [src](https://github.com/eslint/eslint/blob/master/lib/rules/no-unreachable.js) | [test](https://github.com/eslint/eslint/blob/master/tests/lib/rules/no-unreachable.js) | @JayaKrishnaNamburu
- [ ] disallow control flow statements in finally blocks (`no-unsafe-finally`)
  - [docs](https://eslint.org/docs/rules/no-unsafe-finally/) | [src](https://github.com/eslint/eslint/blob/master/lib/rules/no-unsafe-finally.js) | [test](https://github.com/eslint/eslint/blob/master/tests/lib/rules/no-unsafe-finally.js)
- [x] disallow negating the left operand of relational operators (`no-unsafe-negation`)
  - [docs](https://eslint.org/docs/rules/no-unsafe-negation/) | [src](https://github.com/eslint/eslint/blob/master/lib/rules/no-unsafe-negation.js) | [test](https://github.com/eslint/eslint/blob/master/tests/lib/rules/no-unsafe-negation.js) | #89 
- [ ] disallow template literal placeholder syntax in regular strings (`no-template-curly-in-string`)
  - [docs](https://eslint.org/docs/rules/no-template-curly-in-string/) | [src](https://github.com/eslint/eslint/blob/master/lib/rules/no-template-curly-in-string.js) | [test](https://github.com/eslint/eslint/blob/master/tests/lib/rules/no-template-curly-in-string.js)
- [ ] disallow deleting variables (`no-delete-var`)
  - [docs](https://eslint.org/docs/rules/no-delete-var/) | [src](https://github.com/eslint/eslint/blob/master/lib/rules/no-delete-var.js) | [test](https://github.com/eslint/eslint/blob/master/tests/lib/rules/no-delete-var.js)
- [ ] disallow labels that are variable names (`no-label-var`)
  - [docs](https://eslint.org/docs/rules/no-label-var/) | [src](https://github.com/eslint/eslint/blob/master/lib/rules/no-label-var.js) | [test](https://github.com/eslint/eslint/blob/master/tests/lib/rules/no-label-var.js)
- [ ] disallow shadowing of restricted names (`no-shadow-restricted-names`)
  - [docs](https://eslint.org/docs/rules/no-shadow-restricted-names/) | [src](https://github.com/eslint/eslint/blob/master/lib/rules/no-shadow-restricted-names.js) | [test](https://github.com/eslint/eslint/blob/master/tests/lib/rules/no-shadow-restricted-names.js)
- [ ] suggest template literals instead of string concatenation (`prefer-template`)
  - [docs](https://eslint.org/docs/rules/prefer-template/) | [src](https://github.com/eslint/eslint/blob/master/lib/rules/prefer-template.js) | [test](https://github.com/eslint/eslint/blob/master/tests/lib/rules/prefer-template.js)

**Comment by yangshun** [comment]
Some general observations/thoughts while working on the `noDebugger` rule:

- Not clear how to test for both valid and invalid cases. Would be good to have a [format similar to ESLint's](https://github.com/eslint/eslint/blob/master/tests/lib/rules/no-debugger.js) where contributors just specify the valid and invalid patterns along with desired errors
- Might want to sort the exports in `packages/@romejs/js-compiler/transforms/lint/index.ts` alphabetically to reduce the chance of merge conflicts. From looking at the PRs, there will be quite a few merge conflicts as most people add it to the bottom
- Might want to sort the cases within `packages/@romejs/js-compiler/__rtests__/lint.ts` or start a convention of one test file per rule. Lowers the chance of merge conflicts and smaller files are easier to read
- The `unusedVariables` rule is firing on the other lint rules tests. Would be nice to have a way to silence it for other tests

**Comment by JayaKrishnaNamburu** [comment]
Hey is anyone interested in discussing some pointers on implementation of ``no-unreachable`` implementation. I tried some way, but one way or the other few edge cases are failing when tested over **eslint** test rules 😓 😅

**Comment by jloleysens** [comment]
Taking `no-compare-neg-zero`

**Comment by macovedj** [comment]
@JayaKrishnaNamburu Sounds like one of the more fun ones.  I'd be interested in thinking about it.  Got a branch up yet?

**Comment by JayaKrishnaNamburu** [comment]
Sure @JayaKrishnaNamburu i will update it tomorrow and let's discuss there 😄

**Comment by sebmck** [comment]
@JayaKrishnaNamburu 

> Hey is anyone interested in discussing some pointers on implementation of `no-unreachable` implementation. I tried some way, but one way or the other few edge cases are failing when tested over **eslint** test rules sweat sweat_smile

I don't think it would be as straightforward as ESLint since we don't have the same concept of code paths. It's fine if it's not as smart. Rome has a more sophisticated analysis system in `js-analysis` that we can utilize in the far future for something even better.

**Comment by sebmck** [comment]
I've updated the main issue body with the latest PRs.

**Comment by mattsjones** [comment]
My user is @mattsjones not @MattJones btw 😅

**Comment by sebmck** [comment]
Oops, sorry @MattJones :stuck_out_tongue:

**Comment by bsotodo** [comment]
I will work on `no-template-curly-in-string`

**Comment by wgardiner** [comment]
I'll take `no-func-assign`

**Comment by macovedj** [comment]
no-cond-assign please

**Comment by sebmck** [comment]
Yeah we would want the always/only option. Parens seems like an odd escape hatch. Just suppress it if it's what you actually want to mean.

**Comment by JayaKrishnaNamburu** [comment]
> @JayaKrishnaNamburu
> 
> > Hey is anyone interested in discussing some pointers on implementation of `no-unreachable` implementation. I tried some way, but one way or the other few edge cases are failing when tested over **eslint** test rules sweat sweat_smile
> 
> I don't think it would be as straightforward as ESLint since we don't have the same concept of code paths. It's fine if it's not as smart. Rome has a more sophisticated analysis system in `js-analysis` that we can utilize in the far future for something even better.

Sure,  Thank you. I will continue my work then 👍  😄

**Comment by mattsjones** [comment]
Happy to pickup `no-shadow-restricted-names`. ESLint currently only handles `"undefined", "NaN", "Infinity", "arguments", "eval"`. 

I was thinking we should block everything matching `scope.getRootScope().isGlobal(name)`?

**Comment by sebmck** [comment]
Sounds good to me!

**Comment by weblancaster** [comment]
Picking up `no-ex-assign`

**Comment by mitchellhamilton** [comment]
I'll pick up `no-import-assign`

**Comment by zinyando** [comment]
I'm taking on `no-unsafe-finally`

**Comment by ikeryo1182** [comment]
I will try `no-regex-spaces`

**Comment by torifat** [comment]
I'm taking `prefer-template`

**Comment by macovedj** [comment]
I can do `getter-return`

**Comment by sebmck** [comment]
Updated the issue body. Thanks everyone! Super happy and appreciative of all the PRs so far!

**Comment by KevinKelbie** [comment]
I can do `no-empty-character-class`

**Comment by tatchi** [comment]
I would like to try `no-inner-declarations` (hopefully it's not too complex 😄)

**Comment by zinyando** [comment]
I'm going to try to work on `no-extra-boolean-cast`

**Comment by macovedj** [comment]
picking up `prefer-template`

**Comment by KevinKelbie** [comment]
I'll take on `no-invalid-regexp`

**Comment by macovedj** [comment]
Is anybody here stuck/feel like they could use a second pair of eyes on whatever problem they're on?

**Comment by sebmck** [comment]
There's been some changes to structure since this issue was created and many of the PRs submitted. I just created a PR that adds a simple rule #196 and included some instructions that will hopefully be helpful to others.

**Comment by thecodrr** [comment]
@sebmck can you please update the list? I see some rules in the list that are unchecked but are already implemented. Oh and I implemented `no-inner-declarations` rule (#305) since @tatchi never made a PR. So please update accordingly.

**Comment by tatchi** [comment]
@thecodrr actually I did open a PR #142 but we decided to close it. Sorry, I should have added a comment here.

**Comment by thecodrr** [comment]
@tatchi and I should have confirmed (and researched) before jumping to implementation. :laughing: Duplicate efforts. haha

**Comment by sebmck** [comment]
It actually looks like all these rules have been implemented or deferred. If anyone has any other ideas for lint rules, whether ones that already exist, or new ones that are made easier/justified with an easy autofix, please open an issue to discuss!
